# GitHub Pages Configuration for Minimal Website

# Site settings
title: "Minimal - AI-Powered Conversational Experiences"
description: "Transform your static website into an intelligent conversational experience with Minimal's AI-powered platform."
url: "https://minimalapp.github.io"
baseurl: "/minimalweb"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Include directories and files
include:
  - about
  - features
  - integration
  - help
  - guides
  - community
  - careers
  - terms
  - privacy
  - gdpr
  - security
  - contact
  - assets
  - components

# Exclude files
exclude:
  - README.md
  - deploy.sh
  - .gitignore
  - .DS_Store

# SEO and social
lang: es
locale: es_ES

# GitHub Pages specific
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
company:
  name: "Minimal"
  email: "hello@minimal.com"
  
# Social media (optional)
social:
  - name: "GitHub"
    url: "https://github.com/minimalapp"